---
- name: "Создание директории для инвентаря"
  ansible.builtin.file:
    path: "{{ inventory.file | dirname }}"
    state: directory
    mode: '0755'
  delegate_to: localhost
  when: inventory.file | dirname != '.'

- name: "Генерация inventory файла"
  ansible.builtin.template:
    src: inventory.j2
    dest: "{{ inventory.file }}"
    mode: '0644'
    backup: false
  delegate_to: localhost
  vars:
    groups: "{{ vm_groups }}"
    vm_details: "{{ vm_details }}"
    vm_user: "{{ default_vm.vm_user }}"
    ssh_key_path: "{{ default_vm.ssh_key_path }}"
    folder_id: "{{ yc_folder_id }}"
    subnet_name: "{{ default_vm.subnet_name }}"
    image_family: "{{ default_vm.image_family }}"