version: '3.8'

services:
  web:
    build: .
    container_name: shvirtd-web
    ports:
      - "80:5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge