---
- name: "Проверка наличия данных о VM"
  ansible.builtin.fail:
    msg: "Нет данных о VM. Сначала выполните сбор информации."
  when: vm_details is not defined or vm_details | length == 0

- name: "Инициализация vm_groups"
  ansible.builtin.set_fact:
    vm_groups: {}

- name: "Группировка VM по метке ansible_group"
  ansible.builtin.set_fact:
    vm_groups: "{{ vm_groups | combine({item.labels.ansible_group: (vm_groups[item.labels.ansible_group] | default([])) + [item]}) }}"
  loop: "{{ vm_details }}"
  loop_control:
    label: "Группировка {{ item.name }} по ansible_group"
  when: item.labels.ansible_group is defined and item.labels.ansible_group | length > 0

- name: "Группировка VM по ролям"
  ansible.builtin.set_fact:
    vm_groups: "{{ vm_groups | combine({'role_' + item.labels.role: (vm_groups['role_' + item.labels.role] | default([])) + [item]}) }}"
  loop: "{{ vm_details }}"
  loop_control:
    label: "Группировка {{ item.name }} по роли"
  when: item.labels.role is defined and item.labels.role | length > 0

- name: "Добавление группы всех VM"
  ansible.builtin.set_fact:
    vm_groups: "{{ vm_groups | combine({'all_vms': vm_details}) }}"

- name: "Результаты группировки"
  ansible.builtin.debug:
    msg:
      - "Создано групп: {{ vm_groups.keys() | length }}"
      - "Группы: {{ vm_groups.keys() | join(', ') }}"
      - "vm_groups: {{ vm_groups }}"