---
- name: "Создание VM в Yandex Cloud"
  hosts: localhost
  connection: local
  gather_facts: true
  tags: [create-vms, infrastructure]
  roles:
    - yc-vm-role

- name: "Генерация инвентаря"
  hosts: localhost
  connection: local
  gather_facts: true
  tags: [inventory, infrastructure]
  roles:
    - yc-inventory-role

- name: "Настройка ClickHouse"
  hosts: clickhouse
  tags: [clickhouse, database]
  roles:
    - role: clickhouse

- name: "Настройка Lighthouse"
  hosts: lighthouse
  become: true
  tags: [lighthouse, web]
  roles:
    - lighthouse-role

- name: "Настройка Vector"
  hosts: vector
  become: true
  gather_facts: true
  tags: [vector, logs]
  vars:
    clickhouse_host: "{{ hostvars['clickhouse-01']['private_ip'] | default('clickhouse-01') }}"
  roles:
    - vector-role