# phpmyadmin-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        env:
        - name: PMA_HOST
          value: <внутренний_IP_хоста_MySQL>
        - name: PMA_PORT
          value: "6432"
        - name: PMA_USER
          value: <mysql_user>
        - name: PMA_PASSWORD
          value: <mysql_password>
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: phpmyadmin