---
  - src: git@github.com:aleksey-dubrovin/yc-vm-role.git
    scm: git
    version: "v1.0.1"
    name: yc-vm-role    
  - src: git@github.com:aleksey-dubrovin/yc-inventory-role.git
    scm: git
    version: "v1.0.1"
    name: yc-inventory-role    
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse 
  - src: git@github.com:aleksey-dubrovin/lighthouse-role.git
    scm: git
    version: "v1.0.0"
    name: lighthouse-role
  - src: git@github.com:aleksey-dubrovin/vector-role.git
    scm: git
    version: "v1.0.0"
    name: vector-role    
  